### ISSUE TITLE
iOS .env files don't parse variables that have spaces 

### ISSUE THREAD

**Issue by danielwinkler** [react-native-config/react-native-config#394]
`DOT=ENV`
is fine.
But
`DOT = ENV`
is not parsed.

**Comment by danielwinkler** [comment]
Fixed with PR https://github.com/luggit/react-native-config/pull/393

**Comment by rajatrao777** [comment]
Hi,
I have been using this package , android works fine(with/without spaces) but in iOS i was facing issue, after some time i figured out it was due to spacing, it was not able to read as you have mentioned , it is able to read the file but not the content with spaces. 
so i guess its still not fixed :(

**Comment by danielwinkler** [comment]
Yeah, 

maybe @luancurti could have a look at this straight forward PR

**Comment by luancurti** [comment]
@danielwinkler merged! I'll generate another version in `npm` after some tests in a few days

**Comment by luancurti** [comment]
@danielwinkler could you test in current master branch and report here what's the result please?
